### ISSUE TITLE
Finesse the PEP8 requirements for SkyPy

### ISSUE THREAD

**Issue by itrharrison** [skypyproject/skypy#158]
There are a number of the PEP8 requirements which (I think) we would like to bypass / alter.

- Increase the 80 character line limit to 120
- No longer require whitespace around all operators (in particular `**`)

**Comment by Lucia-Fonseca** [comment]
I agree with these suggestions. I wouldn't dismiss all the whitespaces around all operators. I find them very useful for `+`, `-`, `*`, `/` ..., at least to me. But I see how it can be a problem for the power operator

**Comment by ntessore** [comment]
Astropy code style for testing (but see note at top):

```ini
[testenv:codestyle]
# We list the warnings/errors to check for here rather than in setup.cfg because
# we don't want these options to apply whenever anyone calls flake8 from the
# command-line or their code editor - in this case all warnings/errors should be
# checked for. The warnings/errors we check for here are:
# E101 - mix of tabs and spaces
# W191 - use of tabs
# W291 - trailing whitespace
# W292 - no newline at end of file
# W293 - trailing whitespace
# W391 - blank line at end of file
# E111 - 4 spaces per indentation level
# E112 - 4 spaces per indentation level
# E113 - 4 spaces per indentation level
# E301 - expected 1 blank line, found 0
# E302 - expected 2 blank lines, found 0
# E303 - too many blank lines (3)
# E304 - blank lines found after function decorator
# E305 - expected 2 blank lines after class or function definition
# E306 - expected 1 blank line before a nested definition
# E502 - the backslash is redundant between brackets
# E722 - do not use bare except
# E901 - SyntaxError or IndentationError
# E902 - IOError
# E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree
# F822: undefined name in __all__
# F823: local variable name referenced before assignment
skip_install = true
description = check code style, e.g. with flake8
deps = flake8
commands = flake8 astropy --count --select=E101,W191,W291,W292,W293,W391,E111,E112,E113,E30,E502,E722,E901,E902,E999,F822,F823
```

Their [.pep8speaks.yml](https://github.com/astropy/astropy/blob/master/.pep8speaks.yml) sets a 100 character line length. This seems to be a [well-motivated choice](https://github.com/aizatto/character-length).

**Comment by rrjbca** [comment]
I'm certainly in favour of increasing the allowed character line length. I've already seen too many examples of variables given shorter but less meaningful names just to satisfy the line limit. 100 seems sensible to me.

**Comment by rrjbca** [comment]
I was less convinced about whitespace around `**`. But from PEP8:

- Always surround these binary operators with a single space on either side: assignment (=), augmented assignment (+=, -= etc.), comparisons (==, <, >, !=, <>, <=, >=, in, not in, is, is not), Booleans (and, or, not).
- If operators with different priorities are used, consider adding whitespace around the operators with the lowest priority(ies). Use your own judgment; however, never use more than one space, and always have the same amount of whitespace on both sides of a binary operator:

The first rule Implies requiring whitespace around `**` isn't actually part of PEP8. Also since raising to a power is always the highest priority operator, the second rule argues there should not be whitespace around `**` if also using other operators in the same statement. So I'm happy to let that one go too.
