### ISSUE TITLE
Tests that require skypy-data are not skipped if it is not installed

### ISSUE THREAD

**Issue by rrjbca** [skypyproject/skypy#326]
**Describe the bug**
The tests [`test_load_spectral_data`](https://github.com/skypyproject/skypy/blob/master/skypy/galaxy/tests/test_spectrum.py) and [`test_spectral_data_input`](https://github.com/skypyproject/skypy/blob/master/skypy/utils/tests/test_decorators.py) require [`skypy-data`](https://github.com/skypyproject/skypy-data) but are not skipped if it is not installed leading to test failures.

**Expected behaviour**
These tests should be skipped if `skypy-data` is not installed. As an example see how the `HAS_SPECUITLS` flag is used in [`test_spectrum.py`](https://github.com/skypyproject/skypy/blob/master/skypy/galaxy/tests/test_spectrum.py) to similarly skip some tests when `specutils` is no installed.

**To Reproduce**
```
pip install skypy==0.3rc2 pytest-astropy pytest-rerunfailures specutils
pytest --pyargs skypy.galaxy.tests.test_spectrum skypy.utils.tests.test_decorators
```

**Comment by aamara** [comment]
Is this the same as:

Requirement 'skypy-data@https://github.com/skypyproject/skypy-data/archive/master.tar.gz' looks like a filename, but the file does not exist
Processing ./skypy-data@https:/github.com/skypyproject/skypy-data/archive/master.tar.gz
Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '~/Workspaces/skypy-data@https:/github.com/skypyproject/skypy-data/archive/master.tar.gz'

**Comment by aamara** [comment]
I did this:

pip install skypy-data@https://github.com/skypyproject/skypy-data/archive/master.tar.gz
