### ISSUE TITLE
Enable Zenodo DoIs for SkyPy releases

### ISSUE THREAD

**Issue by itrharrison** [skypyproject/skypy#56]
As mentioned after my discussion in Oxford, it is possible to assign a specific DoI to each release version of a code using integration between github and Zenodo:
https://guides.github.com/activities/citable-code/

This means that contributors to a version can be given credit in a citation, rather than credit being frozen in up on a paper release, and new contributors not accruing citations.

The astropy Zenodo record is here:
https://zenodo.org/record/1461593#.Xj0wzxP7QnU

There is a 'cite all versions' option:

> "Cite all versions? You can cite all versions by using the DOI 10.5281/zenodo.1461536. This DOI represents all versions, and will always resolve to the latest one. Read more."

There is an exportable bibtex entry:

`@software{the_astropy_collaboration_2018_1461593,
  author       = {The Astropy Collaboration},
  title        = {{astropy v3.0.4: a core python package for 
                   astronomy}},
  month        = aug,
  year         = 2018,
  publisher    = {Zenodo},
  version      = {3.0.4},
  doi          = {10.5281/zenodo.1461593},
  url          = {https://doi.org/10.5281/zenodo.1461593}
}`

And there is and ADS bibcode:
https://ui.adsabs.harvard.edu/abs/2018zndo...1461536T/abstract

Although Astropy don't do it, it seems possible to add individual names to a release, e.g.:
https://ui.adsabs.harvard.edu/abs/2019zndo...2533376B/abstract

**Comment by rrjbca** [comment]
Been looking into this for v0.1. Astropy manually register new versions in Zenodo rather than using the github plugin and although they don't explain why I can guess some reasons:

- Tags created through GitHub cannot be gpg signed, this must be done on the command line.
- DOI created automatically, which means you cannot include the DOI in the release itself e.g. Zenodo DOI badge on the homepage. With a manual entry you can reserve a DOI in advance of uploading for exactly this purpose.
- We don't want DOIs for pre-releases (alpha, beta, release candidate etc) not sure if Zenodo plugin would create DOIs for these too.

The main advantage I see is that Zenodo will manage 'ownership' of the DOIs via the skypyproject GitHub organization. @aamara would it be possible to setup a skypyproject Zenodo account with credentials that can be shared as appropriate?
